// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBTgyt7PBQg0MTx_KEmMQmrIRHsFgBszE',
    appId: '1:944125810470:web:632a6f31bac7103c8d13e7',
    messagingSenderId: '944125810470',
    projectId: 'fir-flutter-codelab-d6717',
    authDomain: 'fir-flutter-codelab-d6717.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d6717.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJLj0mgIbKyhfA8V7sGv2ikkMbRYbEWWc',
    appId: '1:944125810470:android:25631e55b3b1a9288d13e7',
    messagingSenderId: '944125810470',
    projectId: 'fir-flutter-codelab-d6717',
    storageBucket: 'fir-flutter-codelab-d6717.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqZGP2sKQMQl7YvW4CK5SqvqDsW4eKLYw',
    appId: '1:944125810470:ios:aa0fc1b078326f968d13e7',
    messagingSenderId: '944125810470',
    projectId: 'fir-flutter-codelab-d6717',
    storageBucket: 'fir-flutter-codelab-d6717.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqZGP2sKQMQl7YvW4CK5SqvqDsW4eKLYw',
    appId: '1:944125810470:ios:aa0fc1b078326f968d13e7',
    messagingSenderId: '944125810470',
    projectId: 'fir-flutter-codelab-d6717',
    storageBucket: 'fir-flutter-codelab-d6717.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBTgyt7PBQg0MTx_KEmMQmrIRHsFgBszE',
    appId: '1:944125810470:web:34b4b153870960d38d13e7',
    messagingSenderId: '944125810470',
    projectId: 'fir-flutter-codelab-d6717',
    authDomain: 'fir-flutter-codelab-d6717.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d6717.appspot.com',
  );

}